apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: 172.18.0.2  # control-plane IP
        peer-asn: 64512
        my-asn: 64512
      - peer-address: 172.18.0.3  # worker IP
        peer-asn: 64512
        my-asn: 64512